### ISSUE TITLE
demo 可能不支持node 18

### ISSUE THREAD

**Issue by fullmooooon** [w1301625107/Vue-Gantt-chart#112]
npm i
npm run serve

```
10% building 2/2 modules 0 activeError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
10% building 2/6 modules 4 active ...ef--12-0!C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\babel-loader\lib\index.js!C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\eslint-loader\index.js??ref--13-0!C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\src\main.jsnode:internal/crypto/hash:71ode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\rise2\Desktop\work_test\Vue-Gantt-chart-master\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
```

**Comment by w1301625107** [comment]
这应该是基础库的问题，最好用旧一点node版本，14是可以的
